build: add npm run lint-fix to pre-commit

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,7 +1,13 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
-npm run lint --fix || 
+npm run lint-fix || 
+(
+  echo "Linting failed. Please fix the errors and try again."
+  false;
+)
+
+npm run lint || 
 (
   echo "Linting failed. Please fix the errors and try again."
   false;
